### ISSUE TITLE
remove-on-event should check that parentNode is really the parent

### ISSUE THREAD

**Issue by brianchirls** [ngokevin/kframe#1]
This throws an error in the spotify example, presumably because the element to be removed is not actually attached to the DOM, so `el.parentNode` is null.

**Comment by ngokevin** [comment]
Thanks, this might have been fixed in master, I'll try changing to `parentEl` workaround which we are setting.

**Comment by ngokevin** [comment]
Or I might have to detach the event lsitener after I remove it.

**Comment by ngokevin** [comment]
https://github.com/ngokevin/kframe/commit/a5633b55f3ded79f10ff5e0c0c33742ec7973955
