### ISSUE TITLE
[state] Support binding of unnamed single propertys in components

### ISSUE THREAD

**Issue by mattrei** [ngokevin/kframe#109]
When the component has an unnamed property (_schema_ is empty) the binding to the property does not work (_this.data_ stays empty).

To make the code of small components slick and clean this feature should be added.

**Comment by ngokevin** [comment]
Can you provide an example?

**Comment by mattrei** [comment]
sorry, it's not relevant any more. It just caused an error if I did not define any _default_ or _type_ in the _schema_ dictionary of the element. Sure you have to provide those otherwise the state-component does not how to interpret it!
Closing as not relevant therefore.
