### ISSUE TITLE
layout: TypeError: invalid 'in' operand f.getDOMAttribute(...)

### ISSUE THREAD

**Issue by wmurphyrd** [ngokevin/kframe#116]
Strangely, layout started throwing this error for me even on a production website that hasn't been updated and is using version locked layout and A-Frame links. I'm linking to layout here: https://unpkg.com/aframe-layout-component@^4.3.0/dist/aframe-layout-component.min.js

**Comment by ngokevin** [comment]
4.3.1 should've addressed this, but if you get rid of the caret, `^`, you'll get a true version lock. Try 4.3.0...but it's weird since 4.3.1 is the patch that actually fixes that.

**Comment by wmurphyrd** [comment]
Yeah that was stupid on my part; that link is the opposite of a version lock

**Comment by wmurphyrd** [comment]
Sorry I don't have a reprex for you. The use of layout in adit was factored out by the new wheel-select component, so, if this isn't happening in other implemenations, it may have just been an edge case quirk
