### ISSUE TITLE
[text-geometry] Compatibility with 0.7.0+

### ISSUE THREAD

**Issue by jaredpike** [ngokevin/kframe#117]
I duplicated the vaporwave demo and swapped the version of A-Frame to the latest, which seems to break the component.

https://glitch.com/edit/#!/certain-visitor

**Comment by ngokevin** [comment]
Thanks for filing, if anyone could take a look at it, that'd be great.

**Comment by jaredpike** [comment]
![screen shot 2017-12-21 at 5 35 05 pm](https://user-images.githubusercontent.com/8635832/34277805-5470ecc2-e675-11e7-9de7-23ddebcb6fea.png)

Interesting, I can get it to work locally. Might be an issue with glitch? Feel free to close.
