### ISSUE TITLE
[animation] startEvents vs restartEvents

### ISSUE THREAD

**Issue by madsenfr** [ngokevin/kframe#120]
Hi, this codepen https://codepen.io/MadsenFr/pen/ZaoXEM doesn't work anymore : 
- "Initial position" button was intend to get the squarre back to it's original position.
- Afterward, "Go" button should restart animation.

It seems that restartEvents doesn't exists anymore, because I get : Unknown property `restartEvents` for component/system `animation`.

I managed to make it work https://codepen.io/MadsenFr/pen/NXxJQP, by replacing restartEvents with startEvents and by sending in a row startEvents then pauseEvents to get it back to it's original position (but this method didn't work before, I've tried it). Is it the right way to do it ?
By the way is it possible to source specific version number to keep stability and to have a changelog (like it's done for aframe) ?

**Comment by ngokevin** [comment]
Add a version to the unpkg URL `aframe-animation-component@3.2.x` 

I'll look at adding restartEvents
