### ISSUE TITLE
Animating Attributes yields different behavior than a-animation

### ISSUE THREAD

**Issue by amitchell89** [ngokevin/kframe#125]
Sorry if this is more a question than an issue. I recently upgraded my project from using a-frame in a simple html file to using react / aframe-react etc. and I've noticed the rotation attribute is exhibiting different behavior now. 

A) This rotates the box on its axis so it spins on itself, 
```
<Entity primitive='a-box' animation="property: rotation; dur: 2500; to: 0 360 0; loop: true; fill: forwards;"
            />
```
B) The original A frame way. This makes the object rotate around a central point (0,0)
```
<a-entity>
    <a-box position="0 3 -5.5"></a-box>
    <a-animation attribute="rotation"
           dur="2500"
           fill="forwards"
           to="0 360 0"
           repeat="indefinite">
     </a-animation>
</a-entity>
```

Is there documentation that outlines these differences and how to alter your code to get the desired results?

**Comment by ngokevin** [comment]
Animate the parent.

```
<a-entity animation>
  <a-box></a-box>
</a-entity>
```
