### ISSUE TITLE
[state] suggestion/fyi for expression support

### ISSUE THREAD

**Issue by donmccurdy** [ngokevin/kframe#127]
Noticed that you added boolean operators and thought I'd shoot over an FYI, I have a lightweight library for evaluating arbitrary JS-like expressions: https://github.com/donmccurdy/expression-eval, based on jsep.

I'd been intending to use it with my own state components ([example](https://github.com/donmccurdy/aframe-extras/blob/feat-state-machine/src/state-machine/FilteredEventListener.js)) but have been distracted by other projects, so it's there if you want it :)

**Comment by ngokevin** [comment]
Yeah thanks, I checked it out before! I didn't want to include the jsep dependency and think about parsing the AST when I just needed &&/||. Perhaps if the component starts to support more expressions, but hope I don't have to go there.

**Comment by donmccurdy** [comment]
Cool! Yeah pretty lightweight (only a couple kb i think) but for just the boolean ops it's probably still overkill
