### ISSUE TITLE
Animations not working on Daydream

### ISSUE THREAD

**Issue by Danpollak** [ngokevin/kframe#128]
It seems that Daydream won't support animejs-based animation in scene due to Polyfill stopping the window's requestAnimationFrame after calibration of Daydream device.

I forked anime and changed the requestAnimationFrame to use the requestAnimationFrame from AFRAME scene instead of window.

fork : https://github.com/halolabs/anime-aframe
You can see the changes I've made to anime [here](https://github.com/halolabs/anime-aframe/commit/efc534bae9cd2422fa356038756a82f46bc42350#diff-1b59c9561160b886683db392a86524b9)

**Comment by ngokevin** [comment]
component uses tick now
