### ISSUE TITLE
animation-component / current position instead of property value

### ISSUE THREAD

**Issue by kencessna** [ngokevin/kframe#131]
Hi, thanks for all this! It`s fantastic! here`s my question!

I have a collada-model and 3 arrows and each arrow is a position the model should move to. I left out the "from" property but as discribed it starts from current property value of the entity. I would like it to start always from the new current position, so that it would slowly move from one arrow to the arrow I click.

Thanks for help! Cheers, Can

**Comment by ngokevin** [comment]
Can call `el.components.animation.updateConfig()` or keep the `from` up to date yourself...`startEvents` might also work
