### ISSUE TITLE
debug cursor is on npm but not in this repo

### ISSUE THREAD

**Issue by i3games** [ngokevin/kframe#132]
The `aframe-debug-cursor` component is on [npm](https://www.npmjs.com/package/aframe-debug-cursor-component) with a link to this repo but it is not in the repo. The [direct link from the npm page](https://www.npmjs.com/package/aframe-debug-cursor-component#installation) to  https://github.com/ngokevin/kframe/blob/HEAD/dist is a 404.

**Comment by ngokevin** [comment]
had it named aframe-debug-cursor-component, renamed to debug-cursor https://github.com/ngokevin/kframe/commit/b27d50d0c2c27eec50cd03c3327c659c67b70816
