### ISSUE TITLE
Delay doesn't do anything

### ISSUE THREAD

**Issue by msj121** [ngokevin/kframe#14]
I have obviously added a delay with 50000 milliseconds, which has no change...

I only notice the "delay" keyword once in the source code, and that is to define the schema. Is this just missing in the config or a future feature?

**Comment by ngokevin** [comment]
Thanks, maybe I missed it. I will try to get back to maintaining this component, it needs to be ported to Tween.js because anime.js has a couple issues.

**Comment by softpunch** [comment]
I can confirm the delay not working, just FYI.

**Comment by softpunch** [comment]
(If there are issues with maintaining this component, 
probably remove the link to it in the docs?)

**Comment by Utopiah** [comment]
Might be good to offer a PR with a test on [playAnimation()](https://github.com/ngokevin/kframe/blob/master/components/animation/index.js#L136)

**Comment by ngokevin** [comment]
fixed https://github.com/ngokevin/kframe/commit/01655b868e554e855a480ea072a2e8a0e6943169
