### ISSUE TITLE
[animation] component disables time uniform in shaders

### ISSUE THREAD

**Issue by feiss** [ngokevin/kframe#146]
Using animation component to animate a shader parameter disables the time parameter passed automatically to aframe shaders.

Here, adding a `testAttr` parameter to the example shader from aframe docs:
https://glitch.com/edit/#!/join/6c9a67fb-4d48-4af5-b977-3383ce462f44

**Comment by ngokevin** [comment]
I would animate it directly. `components.material.material.uniforms.testAttr.value`
