### ISSUE TITLE
[animation & layout] Using animation for layout doesn't seem to work

### ISSUE THREAD

**Issue by derhuebiii** [ngokevin/kframe#151]
I am using the following to try to animate the properties of a layout component:

    <a-entity layout="type: box; columns: 4; margin: 1"  position="0 0 -5" animation__fadein="property: layout.margin; dur: 100; easing: linear; from 0; to: 5; startEvents: fadein">

I don't get it to work even if I try to do a simple `rotation` / `position` animation. For geometric entities it works normally.

The native animation component works.

Here is a jsfiddle:
[jsfiddle](https://jsfiddle.net/6ffvusvc/)

**Comment by ngokevin** [comment]
your code had several mistakes in a single line.

`position: layout`, not specifying `margin`, had a `startEvents` specified that was never triggered

`<a-entity layout="type: box; columns: 4; margin: 0"  position="0 0 -5" animation="property: layout.margin; dur: 1000; easing: linear; from: 0; to: 5">`
