### ISSUE TITLE
[look-at] three.js:8247 THREE.Object3D: .getWorldPosition() target is now required

### ISSUE THREAD

**Issue by machenmusik** [ngokevin/kframe#152]
Using latest A-Frame master, look-at component now apparently fires lots of these warnings...
`three.js:8247 THREE.Object3D: .getWorldPosition() target is now required`

**Comment by zeropaper** [comment]
I did noticed that too and changing the following line
https://github.com/ngokevin/kframe/blob/e48f8cdb4911d7d7ee04e6c879d3b996eb313ad4/components/look-at/index.js#L89
to
```js
var wpVector = new THREE.Vector3();
target3D.getWorldPosition(wpVector);
target = object3D.parent.worldToLocal(wpVector);
```
fixed the issue

**Comment by sbrudz** [comment]
@zeropaper Thanks for posting this fix.  One improvement I'd recommend would be to instantiate wpVector outside of the tick() function (in init() for example).  This will reduce the memory usage of the component since it won't be creating a new Vector3 every tick.

**Comment by ngokevin** [comment]
https://github.com/ngokevin/kframe/commit/685433c840d8d9585193f84cf5e0603ce7c9617f
