### ISSUE TITLE
AudioAnalyser on mobile browsers?

### ISSUE THREAD

**Issue by chrislatorres** [ngokevin/kframe#153]
Hi Kevin,

As someone starting out with aframe, I'm having a lot of fun experimenting with the set of components you've released. I've been trying to get the waveform AudioAnalyser example to work on mobile browsers (Android Chrome, Android Firefox, Oculus Go browser), but the audio and visualizations will not play even if it works fine on desktop browsers.

**Comment by ngokevin** [comment]
Don't think it will work well on mobile browsers, media is crippled and annoying on mobile browsers.
