### ISSUE TITLE
[animation] Error when adding a second animation component to a single entity

### ISSUE THREAD

**Issue by gabrielgrant** [ngokevin/kframe#159]
Adding a second animation component to a single entity results in the following error:
```
index.js:457 Uncaught (in promise) TypeError: Cannot read property 'property' of undefined
    at NewComponent.stopRelatedAnimations (index.js:457)
    at NewComponent.beginAnimation (index.js:191)
    at NewComponent.createAndStartAnimation (index.js:179)
    at NewComponent.update (index.js:122)
    at NewComponent.updateProperties (aframe-master.js:72453)
    at HTMLElement.value (aframe-master.js:71211)
    at HTMLElement.value (aframe-master.js:71185)
    at entityLoadCallback (aframe-master.js:70983)
    at emitLoaded (aframe-master.js:71812)
```
With the following scene: 
```
<a-scene>
  <a-camera position="5 2 5" rotation="-10 45 0" spectator="true"></a-camera>
  <a-box
  color="#EF2D5E"
  animation__first="property: height; dur: 10000; to: 10"
  animation__second="property: width; dur: 10000; to: 10"
></a-box>
</a-scene>
```

using aframe-animation-component v4.2.0 with A-Frame v0.8.2

**Comment by gabrielgrant** [comment]
MVCE: https://github.com/gabrielgrant/aframe-animation-property-error-test/compare/root...master

**Comment by gabrielgrant** [comment]
Woops, above was the code. Here's the compiled version demonstrating the error: https://gabrielgrant.github.io/aframe-animation-property-error-test-build/

**Comment by gabrielgrant** [comment]
Interestingly, adding `autoplay: false` to [the first animation](https://github.com/gabrielgrant/aframe-animation-property-error-test/compare/root...master#diff-f63965ba48df687541db46e0e1b2c2ecR5) causes the error to go away (and the second animation to proceed as expected), but adding `autoplay: false`  to the second animation still causes an error to appear when the animation runs

**Comment by ngokevin** [comment]
Use scale. height/width changes geometry which recalculates the geo.

**Comment by RandomCouch** [comment]
I'm having the same issue with the latest version of aframe-animation-component (5.1.2). Was this already fixed? If so what am I doing wrong?
