### ISSUE TITLE
npm release does not include source

### ISSUE THREAD

**Issue by cjroth** [ngokevin/kframe#16]
It would be awesome if I could pick and choose modules to include in my project:

`import * from 'kframe/text` or `import { 'text' } from 'kframe'`

But this doesn't work with the current npm release because that only includes the `dist` directory.

Also, it would be great if the GitHub releases page listed releases:

https://github.com/ngokevin/kframe/releases

**Comment by ngokevin** [comment]
I will be removing the super bundle and recommend including components individually.

The Registry will later have a service to build bundles of components

**Comment by ngokevin** [comment]
Super bundle removed
