### ISSUE TITLE
Split components into separate repos

### ISSUE THREAD

**Issue by gabrielgrant** [ngokevin/kframe#160]
First, thanks so much for all of this -- these components are super valuable.

I'm sure there are very good reasons to have this all in one repo, and I know splitting it up would be pretty annoying to do. But NPM maintainers have [steadfastly refused to support monorepo layouts](https://github.com/npm/npm/issues/2974#issuecomment-169451651), making it difficult to work with/on the individual components and include them in other projects

**Comment by ngokevin** [comment]
Won't fix, if anyone wants a master build, can clone the repo + build. I place the burden on developers that need that in those case since it would be unmaintainable for me to have 30 different repos

**Comment by gabrielgrant** [comment]
Fair enough, thanks for the reply/explanation
