### ISSUE TITLE
rotation animations always try to restart regardless of "from" attribute

### ISSUE THREAD

**Issue by beefster** [ngokevin/kframe#163]
When resuming an animation of rotation, my entities always restart from the default value regardless of the absent "from" attribute. A possible workaround was to dynamically pass the current rotation as the "from" value before resuming, which almost works, but for about a single frame the entity briefly assumes its default rotation then snaps to the from value before animating.

demonstrated here: https://accurate-amusement.glitch.me/

**Comment by beefster** [comment]
I should add that i'm not 100% certain that the single glitchy frame is the from value, or the to value, didn't think about that as they look identical... Also It's possible that this behavior also occurs with attributes other than rotation. I will experiment more and report back.

**Comment by YunzheZJU** [comment]
Probably same problem as yours.

**Comment by ngokevin** [comment]
`startEvents` will restart the animation. stick only to resumeEvents, have a different name for each
