### ISSUE TITLE
link component title disappears when used with look at component, but only at certain locations relative to user.

### ISSUE THREAD

**Issue by mirzu** [ngokevin/kframe#167]
We ran into a strange error with the Link Component and Look-at component. I'm posting this ticket for both because I'm not sure if this should be fixed in both or one of the components. 

When a link uses the look-at component the title disappears if it is in certain locations in the scene, but not in others. The underlying issues appear to be in the code that creates the view into the portal. 

In the example, you can look to the right and see the missing title. If you move away from the portal you can see the title reappear. The same error occurs when links are places at certain rotations around the user, but not in others.

- A-Frame Version: 0.8.2
- Platform / Device: Tested on Android Chrome and desktop 
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/near-equinox

![hello__webvr__-_a-frame](https://user-images.githubusercontent.com/251658/41869260-17abae1c-787e-11e8-9656-5096ed890bfb.png)

**Comment by ngokevin** [comment]
text `side: double`

**Comment by techninja** [comment]
Trying this out, `side: double` as expected displays the text backwards instead of simply making it invisible on its reverse face. Stupid idea: provide two single sided text entities that occupy the same space but are 180 degrees flipped from each other so they retain readability regardless of how they're viewed.

**Comment by mirzu** [comment]
I think this issue has to do with the logic inside the link component, and for our use-case the easiest solution is to simply provide our own styling for the link component, but it might expose a problem with the logic in the link component since it crops up depending on where the link it placed in the scene coordinate space. Ideally, the link and the look-at component would "just" work together regardless of where in the scene they are placed. 

The quick fix for us is to simply use the link with ```visualAspectEnabled``` and provide our own styling, or make our own link component that doesn't have the complicated portal logic included.

**Comment by ngokevin** [comment]
You will need two text entities if you want them to display the same both sides.

See https://github.com/supermedium/gunters-of-oasis for custom portal
