### ISSUE TITLE
How can i center-align TextGeometry or get the width?

### ISSUE THREAD

**Issue by eyaler** [ngokevin/kframe#168]
How can i center-align TextGeometry or alternatively get the width and align manually?

**Comment by ngokevin** [comment]
Calculate bounding box of the entity, align by shifting half the bounding box size

**Comment by eyaler** [comment]
for reference this solved it for me:

// Create the element and hide it
var newEl = document.createElement('a-entity');
newEl.setAttribute('text-geometry', 'value: '+text_str+'; font: #myfont; size: 0.5; height:0.05');
newEl.setAttribute('material', "color: red; opacity: 0;");

// Wait until the object registers in the scene graph to center and show it
setTimeout(()=>{newEl.object3D.children[0].geometry.center();
                           newEl.setAttribute('material', "opacity: 1;");
                          }, 250);
