### ISSUE TITLE
`reverse-look-controls` breaks mouse handlers when script is loaded after scene markup

### ISSUE THREAD

**Issue by evvvritt** [ngokevin/kframe#17]
Hi, I found that loading the aframe scripts after it's markup breaks the mouse event handlers completely.

[Broken (jsfiddle)](https://jsfiddle.net/evvvvritt/2q1xhwb6/3/)

**Solution**

load with vanilla `look-controls`, set 'reverse-look-controls', then remove 'look-controls'
[jsfiddle](https://jsfiddle.net/evvvvritt/2q1xhwb6/4/)

**Comment by ngokevin** [comment]
We have added warnings in A-Frame to not do this.

Documentation now tells to put scripts before a-scene as well.

https://aframe.io/docs/0.4.0/guides/#starting-with-html
https://aframe.io/docs/0.4.0/guides/writing-a-component.html
