### ISSUE TITLE
[state] error when using bind-for and bind components in the same entity

### ISSUE THREAD

**Issue by feiss** [ngokevin/kframe#170]
if I use a `bind` component with a `bind-for` component in the same entity, it throws this error:
```js
  TypeError: this.bindRootEl is null   (aframe-state-component.js:387)
```
Example:
```html
<a-entity bind__visible="showItem" bind-for="for: item; in: items"></a-entity>
```
if I remove `bind__visible`, no error is thrown.

**Comment by ngokevin** [comment]
Okay, I get it now.

**Comment by ngokevin** [comment]
This should be fixed: `if (bindForEl && bindForEl !== this.el) {` as of 10 days ago

https://github.com/ngokevin/kframe/commit/0d7b8bcdb121ea2241965ae828fa5a41c31f0559

Try bumping your node modules?
