### ISSUE TITLE
animationend event / finished callback? 

### ISSUE THREAD

**Issue by spencercap** [ngokevin/kframe#172]
i know you can listen for animationend events using the <a-animation> style of a-frame animations, so is there an equivalent for this approach?

**Comment by dsinni** [comment]
If you're referring to `aframe-animation-component`, listen for `animationcomplete`.


animationcomplete | Animation completed. Event detail contains name of animation.
-- | --

https://github.com/ngokevin/kframe/tree/master/components/animation
