### ISSUE TITLE
[state] array bind for not updating when the array start empty

### ISSUE THREAD

**Issue by arthurmougin** [ngokevin/kframe#176]
I have a bind-for working when the array has value, 
but when it starts empty and i add values, it doesn't render them.

https://glitch.com/edit/#!/join/3fc06fc5-d3a9-458d-83cc-ca7aa0b0508b

**Comment by disregardfiat** [comment]
Doesn't look like you've found any resolution? i'm also curious about this edge case as it seems to be my stress point as well.

**Comment by ngokevin** [comment]
The values need to be `push`ed to the array, not rewriting the array. And the state has to trigger a change to flush to the application.
