### ISSUE TITLE
[layout] marginColumn and marginRow are undefined

### ISSUE THREAD

**Issue by WellanDraco** [ngokevin/kframe#177]
Thoses properties aren't defined the way they are presented in the doc.

![image](https://user-images.githubusercontent.com/26094902/43047122-cede6610-8da0-11e8-8f20-f42967af8f10.png)

https://glitch.com/edit/#!/join/c2aab611-deb7-41d8-ad64-809a4256de04

**Comment by ngokevin** [comment]
the version there is out of date (try `@5`)

**Comment by WellanDraco** [comment]
the version @5 don't exist on unpkg.com
https://unpkg.com/aframe-state-component@4.6.0/

**Comment by dsinni** [comment]
@WellanDraco That's the wrong component.

https://unpkg.com/aframe-layout-component/
