### ISSUE TITLE
Handle click events with orbit-controls

### ISSUE THREAD

**Issue by ShashankaNataraj** [ngokevin/kframe#178]
Hi, Im trying to handle mouse click events with orbit controls. How do I accomplish this?

**Comment by garyritchie** [comment]
You can emit events and listen for them in functions: https://aframe.io/docs/0.8.0/introduction/javascript-events-dom-apis.html#events-and-event-listeners

...And there's the [event-set](https://github.com/ngokevin/kframe/tree/master/components/event-set) component bundling much of that functionality described here: https://aframe.io/docs/0.8.0/introduction/interactions-and-controllers.html#handling-events-with-event-set-component

**Comment by paulina-grunwald** [comment]
Hey. What you need to do is use aframe-mouse-cursor-component (https://github.com/mayognaise/aframe-mouse-cursor-component) and then to add to your scene <a-scene cursor="rayOrigin: mouse">.  You will be able to click with the mouse then while using orbit controls.

**Comment by ShashankaNataraj** [comment]
@ngokevin thanks, that worked!
