### ISSUE TITLE
Rotate object around model

### ISSUE THREAD

**Issue by nirajupadhyay11** [ngokevin/kframe#179]
Hi,

I am trying to rotate a box around a model. Here is my code - 

```
<head>
  <title>My A-Frame Scene</title>
  <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
  <script src="https://unpkg.com/aframe-orbit-controls@1.0.0/dist/aframe-orbit-controls.min.js"></script>
  <script src="https://unpkg.com/aframe-supercraft-loader@1.1.3/dist/aframe-supercraft-loader.js"></script>
</head>

<body>
  <a-scene>
    <a-entity id="super" supercraft-loader="name: better-reaction" ></a-entity>

    <a-entity camera look-controls orbit-controls="target: 0 1.6 -0.5; minDistance: 0.5; maxDistance: 180; initialPosition: 0 5 15">
        <a-box position="0 1.6 -21" color="red"></a-box>
    </a-entity>
  </a-scene>
    
</body>
```
and codepen: https://codepen.io/nirajupadhyay11/pen/RBBpbd

However, the entire model rotates on dragging the mouse, instead of just the box. 

Could you please help me with this?

Thanks,
Niraj

**Comment by garyritchie** [comment]
Hi Niraj,

aframe-orbit-controls are for _controlling the A-Frame camera_ around a target. Please take a look at [aframe-animation-component](https://github.com/ngokevin/kframe/tree/master/components/animation/). For triggering the animations you might also use [aframe-event-set-component](https://github.com/ngokevin/kframe/tree/master/components/event-set/).

With that combination you'll still be able to view your scene "turntable" style while having your box animating separately. Is that what you're after?

**Comment by nirajupadhyay11** [comment]
Thank you Gary for responding. Actually, the result I am after is keeping the box and the model fixated at their position but when the mouse is dragged, the box should rotate around it's center. 

I am trying to get this to work so that, in my game that I am developing, I can have a 3d gun model point to different directions based on mouse drag. Their are other 3d models in the game such as trees and rocks but they should remain in their position when the mouse is dragged. 

I am sorry if I was not able to explain it more clearly earlier.

**Comment by garyritchie** [comment]
Ah, then check out this example for writing a component: https://aframe.io/docs/0.8.0/guides/building-a-basic-scene.html#adding-interaction -- this + the last codepen example could be combined. I'm not sure if a component already exists for what you want to do so you'll need to write it. :-)

This is also a good reference: https://aframe.io/docs/0.8.0/introduction/javascript-events-dom-apis.html and you can review the code for any of the available aframe components out there. Hope this helps you get started.

**Comment by ngokevin** [comment]
yeah, you'll need to write a component if you want the unique case of rotating only one model when a mouse is dragged. reading look-controls source code may help
