### ISSUE TITLE
[state] Does not allow declarative comparisons of numerical state values

### ISSUE THREAD

**Issue by dsinni** [ngokevin/kframe#185]
Hi, Kevin.

I'm currently using/testing in the latest `4.7.0` version, and it appears that it is not possible to make declarative comparisons against numerical state values.

Example:
`<a-entity ... bind__visible="level === 4"></a-entity>`

If the state value is stored a string (`"4"`), then it works, but that requires manually parsing to and from string/number if it's necessary to manipulate the number.

I wasn't sure if this was by design, so I just thought I'd mention it.

I'm not sure if it would be possible to also add the ability to make <, >, <=, >=, <==, >== comparisons declaratively, but would be a cool feature. Let me know if that's something I should open an enhancement request for.

Thanks for a great component.

**Comment by ngokevin** [comment]
Yeah. I think perhaps to keep the internals simple / performant and not add too much syntax, I'd keep track of the levels as bools. Can be done in `computeState()` or something, then like `bind__visible="level.volcano"`.

**Comment by dsinni** [comment]
Ah, good point there, but then one would need to have a handler to disable every other level upon updating, if they were exclusive, no? Which is fine, I suppose; it just adds an extra step.

In the spirit of keeping things declarative, I thought it would be beneficial to be able to compare directly in the HTML.

Maybe `level` wasn't the best example. Consider something like `bind__visible="points === 100"` and several binds like it that would do something different at various point levels. This is also where I thought something like `bind__visible="points >== 100"` would come in handy.

I've created handlers like below for my use cases:
```js
lt: function ( state, action ) {
  return state[action.prop] < action.value;
},

gt: function ( state, action ) {
  return state[action.prop] > action.value;
}
```
And then use it in an entity like below:
```html
<a-entity ... bind__visible="gt( prop: points, value: 100 )"></a-entity>
```

And that seems to work fine. If that's how you recommend things should be moving forward, that's all good. I just figured these could be some suggestions to make it easier to implement, declaratively, out of the box. 

I must admit, that I don't fully understand all of the documentation, so I may be missing something and would love your guidance if you have the time.

For instance, my understanding of `computeState` is that you compute a state solely based on other state values, but can you somehow check against an arbitrary value, without writing multiple computed states?

It would seem kind of repetitive to do something like:

```js
computeState: function ( state, payload ) {
  state.isOver20  = state.points > 20;
  state.isOver40  = state.points > 40;
  state.isOver50  = state.points > 50;
  state.isOver100 = state.points > 100;
  . . .
  . . .
}
```
Is there any way to do all of this with one computed state? I'm also not sure what the `payload` is or how that is meant to be used. I didn't see anything in the docs about it.

Again, thanks for an already great component; I'm just trying to make sure I'm completely grasping the concept and utilizing best practices, with the possibility of coming up with some ideas to make it even more useful if they meet your requirements.

**Comment by ngokevin** [comment]
The spirit is never to keep everything 100% declarative. If it gets more complex, create a component that takes the points and does the logic needed. 

Not sure how the lt/gt is working.

computeState is called after every action and is passed the action's event detail. Your computeState above could be a loop over an array. I think the component simplifies things enough that you occasionally need to compute state which devolves down to extremely basic JS.

**Comment by ngokevin** [comment]
Compute state is a function that is called after any of those event names you specify in your state fire. it’s used to compute state based on other state. It’s pretty much declarative. Just try it.

**Comment by dsinni** [comment]
Right on. I've got you there. I've used `computeState` successfully for a number of things; I just wasn't fully understanding your suggestion of how to make comparisons against multiple `point` values (for example) by looping over an array and not creating several boolean state properties as a result.

Without the loop, but wouldn't the result be the same?
```js
computeState: function ( state, payload ) {
  state.pointsEqual100 = state.points === 100;
  state.pointsOver10 = state.points > 10;
  state.pointsOver20 = state.points > 20;
  state.pointsOver30 = state.points > 30;
  . . .
}
```
```html
<a-entity bind__visible="pointsEqual100"><a-entity>
<a-entity bind__visible="pointsOver10"><a-entity>
<a-entity bind__visible="pointsOver20"><a-entity>
<a-entity bind__visible="pointsOver30"><a-entity>
```

Rather than just being able to do something like this without computed state:
```html
<a-entity bind__visible="points === 100"><a-entity>
<a-entity bind__visible="points > 10"><a-entity>
<a-entity bind__visible="points > 20"><a-entity>
<a-entity bind__visible="points > 30"><a-entity>
```

Thanks for the separate component example; that makes a lot of sense and I have used a similar approach. I was just hoping to be able to use reusable logic within the state component for simple comparisons rather than having to incorporate it into several components. I suppose I could use a separate system for that, though.

I understand if this would add unwanted complexity to the component. Just wanted to throw this out there to get your thoughts. Feel free to close this issue if it's a hard no. :)

Would definitely benefit greatly from more robust working examples if you ever find the time, especially in conjunction with static templating, since that combination has been recommended over using `aframe-react`. I've found very few examples of them being used together. The gist is simple enough to grasp, but I think many would benefit from understanding how it was designed to be implemented.

Thanks again for your time.

**Comment by ngokevin** [comment]
It’s not that it’s recommended over aframe-react persay, it’s that React and friends are very poor tools for VR and I’ve seen it cause more distraction and trouble than help.

Can create a component that takes the points and threshold and handles appropriately.

**Comment by ngokevin** [comment]
I'm updating the state component to evaluate expressions rather than trying to parse so things like this will be supported now!

**Comment by ngokevin** [comment]
I think for `bind-for`, I removed the use of using `bind__` within the `bind-for` to target the iterated item. There's a `bind-item__` component to use for that now. I have also have a new  `updateInPlace` for `bind-for` that is more performant. Everything else should work.

**Comment by ngokevin** [comment]
You just can't like have colons/semicolons in the expression yet because it will break the style parser. But for like ternaries you can use `foo && bar || baz`. Would need to patch A-Frame to allow escaping those.
