### ISSUE TITLE
[animation] Adding Second Animation to entity fails

### ISSUE THREAD

**Issue by victorsh** [ngokevin/kframe#188]
I'm trying to use setAttribute and the animation component to set several animations to a component. The first animation with attribute as 'animation' work fine, but when using something like 'animation_rotate' it returns the error below. Is there anyway to get around this? Thanks in advance!
![gwu-code-error](https://user-images.githubusercontent.com/5401206/45463286-5de40200-b6c0-11e8-8c14-91c67c146404.png)
![gwu-error](https://user-images.githubusercontent.com/5401206/45463322-81a74800-b6c0-11e8-93cd-29500638c64e.png)

**Comment by ngokevin** [comment]
has the scene initialized by the time this function is run? the code should be contained within a component

**Comment by victorsh** [comment]
Yes for sure, I'm calling the function manually after the scene has loaded. This code works if I only set 1 animation. I also realized that the name of the attribute doesn't matter, I changed the name of the first animation to 'animation__rotator' and it worked. It seems to not be able to set more than one animation attribute.

**Comment by dsinni** [comment]
I can confirm that this works in A-Frame `0.8.2` with `aframe-animation-component` `5.1.0` (current version) when doing so from within components. Components are your friends. :)

Here is a working demo adding animations to a static entity and a dynamically generated one:

**Code**:
https://glitch.com/edit/#!/capable-flier

**Demo**:
https://capable-flier.glitch.me/

**Comment by victorsh** [comment]
Thanks @dsinni , I was able to get this working with the Aframe component as you suggested.

**Comment by ngokevin** [comment]
thanks @dsinni
