### ISSUE TITLE
Most if not all examples are broken.

### ISSUE THREAD

**Issue by mattmillerart** [ngokevin/kframe#19]
Getting lots of console errors which prevent the demos from running in 3d. Below is a log sample from the animation demos. 

```
VRDisplay.getPose() is deprecated. Please use VRDisplay.getFrameData() instead.
build.js:34 VREyeParameters.fieldOfView is deprecated. Please use projection matrices provided by VRFrameData instead.
708build.js:34 submitFrame must be called within a VRDisplay.requestAnimationFrame callback.

```

I'm running Chrome webvr build, its the most recent or second most recent build available. 

Thanks! 
Matt

**Comment by ngokevin** [comment]
Thanks, just have to update the A-Frame version in my examples maybe.

**Comment by ngokevin** [comment]
I think this was on Chromium, it was starting to lag a bit in development but now the polyfills and such are all updated.
