### ISSUE TITLE
[orbit-controsl] example does not work. look-controls must be disabled!

### ISSUE THREAD

**Issue by mattrei** [ngokevin/kframe#196]
I was wondering for quite some time, why the orbit-controls example does behave so strangely and I found out that the look-controls must be disabled or completely removed for the orbit-controls to work as expected.
 
Please remove the look-controls component from the example and document that both components (look-controls and orbit-controls) do not work simultaneously. 

Thx for the great work you do!

**Comment by ngokevin** [comment]
https://github.com/ngokevin/kframe/commit/5383ec6aeca4388134b55e37487b821627548a6f
