### ISSUE TITLE
How to use Animation Events (animationbegin, animationcomplete, etc)

### ISSUE THREAD

**Issue by masterofshapes** [ngokevin/kframe#2]
I tried using the animation complete event

`<a-entity id="plane" geometry="primitive: plane;width:0.5;height:0.5;depth:0.5;" animation="property: scale; from:0 0 0;to: 1 1 1;dur:3000;"></a-entity>`

and then added an event listener

`document.getElementById("cursor").addEventListener("animationcomplete", function(){ console.log("Animation Complete!"); });`

using the events animationbegin or animationcomplete never fire off an event. The animation does work though. Is this a bug or should the events used in a different way?

Thanks

**Comment by ngokevin** [comment]
Sorry my docs were off. I've since changed the code to match the docs.
