### ISSUE TITLE
ReferenceError: i is not defined @ aframe-state-component

### ISSUE THREAD

**Issue by adrianirwin** [ngokevin/kframe#204]
Line 77 of [kframe/components/state/src/bind-for.js](https://github.com/ngokevin/kframe/blob/master/components/state/src/bind-for.js)

`(i = 0; ...` <- add `let`

All the rest of the `for` loops have `i` declared with `let`, looks like this one just got missed.

**Comment by ngokevin** [comment]
Thanks!
