### ISSUE TITLE
layout doesn't take into account removed entities

### ISSUE THREAD

**Issue by Utopiah** [ngokevin/kframe#21]
Adding entities to a layout appends them correctly.
Removing entities then adding entities though doesn't reallocate the empty slots. It might be difficult to keep track of them but into supporting it leads to, arguably, unexpected behavior :

Example http://jsbin.com/qadosi/edit?html,output

**Comment by ngokevin** [comment]
A-Frame has detached events now, just need to recall the layout like we do for attached events

**Comment by ngokevin** [comment]
https://github.com/ngokevin/kframe/commit/e6221aca74e4f7d9674a0fbdd2b11af3cf2503de

**Comment by Utopiah** [comment]
Doesn't seem to work in the example I gave, entities are overlapping, maybe I'm missing something.
