### ISSUE TITLE
Removing animation component does not stop animation from running

### ISSUE THREAD

**Issue by i3games** [ngokevin/kframe#26]
Removing the animation component from an element should stop the animation. Currently it does not. 

Code to reproduce: [https://gist.github.com/i3games/8a9276e2673d29364c089f084049638b](https://gist.github.com/i3games/8a9276e2673d29364c089f084049638b) 

I think it is due to to a wrong parameter is handed to anime.js.

(This might have been reported as #13).

**Comment by i3games** [comment]
BTW if you pull animation from rawgit, i.e. [https://raw.githubusercontent.com/ngokevin/kframe/master/components/animation/dist/aframe-animation-component.js](https://raw.githubusercontent.com/ngokevin/kframe/master/components/animation/dist/aframe-animation-component.js) you will get an older version containing anime.js 1.1.0 (the current version on github [https://raw.githubusercontent.com/ngokevin/kframe/master/components/animation/dist/aframe-animation-component.js](https://raw.githubusercontent.com/ngokevin/kframe/master/components/animation/dist/aframe-animation-component.js) has anime.js 1.1.1). 

The older version does not have this error; the current version has.

**Comment by ngokevin** [comment]
Seems to work now ```document.querySelector('a-cylinder').removeAttribute('animation__scale');```

**Comment by ngokevin** [comment]
https://ngokevin.github.io/kframe/components/animation/examples/events/

`document.querySelector('[animation__position]').removeAttribute('animation__position');`

**Comment by i3games** [comment]
can confirm it works now.
