### ISSUE TITLE
[components/layout] Position attribute for the entity with a layout component is the center of the first child entity, rather than the center of the top level entity

### ISSUE THREAD

**Issue by beccannlittle** [ngokevin/kframe#27]
I would expect the position attribute of the top level entity (the one with the layout component) to refer to the center of that entire entity. For example, I'm trying to make a menu that is slightly rotated along the y axis. I would expect the following code to result in all 5 planes nicely centered, but I don't get that:

```html
<!-- Menu -->
<a-plane position="1 4 20" rotation="0 -15 0" scale="4 4" color="#2b2b2b" opacity="0.8"></a-plane>
<a-entity position="1 5 20.01" layout="type:line; margin:1.1" rotation="0 -15 0">
    <a-plane scale="1 .5" color="#fff" opacity="0.8"></a-plane>
    <a-plane scale="1 .5" color="#fff" opacity="0.8"></a-plane>
    <a-plane scale="1 .5" color="#fff" opacity="0.8"></a-plane>
</a-entity>
<a-plane position="1 3.5 20.01" rotation="0 -15 0" scale="3.2 2" color="#fff" opacity="0.8"></a-plane>
```

<img width="637" alt="screen shot 2017-01-11 at 1 01 17 pm" src="https://cloud.githubusercontent.com/assets/6414050/21866938/621ae38a-d809-11e6-8c9f-1400d05594e2.png">

In order to get these aligned, I have to finagle the top level entity into place through trial and error:

```html
<a-entity position="-.1 5 19.75" layout="type:line; margin:1.1" rotation="0 -15 0">
```

![screen shot 2017-01-11 at 2 43 25 pm](https://cloud.githubusercontent.com/assets/6414050/21867657/5bddc958-d80c-11e6-9d3a-c1a5e9bc93e2.png)

Even after messing with it for a while its still not perfectly centered, because I have to modify both the x and the z positions each time.

This may be more of a feature request than an issue, because there may be cases where you'd want the position to represent the center of the first child entity... it just makes more sense to me semantically the way I've described above.

**Comment by beccannlittle** [comment]
**Solution**: wrap the UI in an entity that you use for absolute positioning (including rotation); position everything else relative to each other, thus basically being able to work in 2D. 

```html
<!-- Menu -->
<a-entity position="1 3.5 20" rotation="0 -15 0">
  <a-plane scale="3.7 4" color="#2b2b2b" opacity="0.8"></a-plane>
  <a-entity position="-1.1 1.5 0.01" layout="type:line; margin:1.1">
    <a-plane scale="1 .5" color="#fff" opacity="0.8"></a-plane>
    <a-plane scale="1 .5" color="#fff" opacity="0.8"></a-plane>
    <a-plane scale="1 .5" color="#fff" opacity="0.8"></a-plane>
  </a-entity>
  <a-plane position="0 0 0.01" scale="3.2 2" color="#fff" opacity="0.8"></a-plane>
  <a-plane position="0 -1.5 0.01" scale="3.2 .5" color="#fff" opacity="0.8"></a-plane>
</a-entity>
```

![screen shot 2017-01-17 at 12 32 43 pm](https://cloud.githubusercontent.com/assets/6414050/22036674/8ed63684-dcb1-11e6-8a34-d728b03d5a9c.png)

I still think the position on the entity with the layout component should refer to the center of that entity and not the center of its first child, but my situation is not as frustrating as I originally thought.

**Comment by ngokevin** [comment]
Thanks. It's harder to center things in WebGL because we have to calculate the lengths. In 2D, it's easy since there's a layout engine. I'll try to find a way to calculate those lengths and see if we can do it automatically.

**Comment by paracycle** [comment]
@ngokevin Wouldn't it be possible to calculate offsets from the center element in the list (or grid for multiple rows)? I've been using the layout component for linear layouts and had to resort to container or positioning tricks like @beccannlittle when I suddenly realized that I can position each item according to `position[0] = (column - (data.columns.length - 1)/2) * marginColumn` which aligns the center of the middle item for odd number of cards or midway between the center two items for even number of cards at the center of the entity. The same can be done for multiple rows as well.

I'd be willing to cut a PR with the change if you are interested in this solution. But it will break all existing usages of the component.
