### ISSUE TITLE
animation component: when "from" not set, it uses the default value instead of current one

### ISSUE THREAD

**Issue by radenui** [ngokevin/kframe#3]
First of all, thanks for all your work!

Code sample:
```
<a-box 
        position="0 1 -2"
        rotation="30 30 0"
        color="#87CEEB"
        roughness="0.8"
        scale="1 1 1"
        animation__mouseover="property: scale; startEvents: mouseenter; to: 1 2 1; dur:500"
        animation__mouseleave="property: scale; startEvents: mouseleave; to: 1 1 1; dur:500"
    >
</a-box>
```

Here there is no "from" attribute set and it seems like it's using the default `scale` value as "from".
In this case, the second animation jus not works as `scale` goes from "1 1 1" to "1 1 1".

I would expect the component to use the current `scale` value as "from".
Is it a normal behavior?

Thanks !

**Comment by ngokevin** [comment]
Thanks, possibly a bug. I will probably get around to rewriting it to tween.js with unit tests. For now, I guess you can manually set `from`?

**Comment by radenui** [comment]
Sure.
Reviewing your code, it seems like the `from` is calculated at `update` time where it should be calculated at execution time. 
``` javascript
function configDefault (el, data, config) {
  var from = data.from || getComponentProperty(el, data.property);
  return AFRAME.utils.extend({}, config, {
    targets: [{aframeProperty: from}],
    aframeProperty: data.to,
    update: function () {
      setComponentProperty(el, data.property, this.targets[0].aframeProperty);
    }
  });
}
```
So this bug may appear only when animations are triggered by events and their properties have changed between update and the event?

**Comment by ngokevin** [comment]
I see. Yeah, I think tween.js is the superior API, which is what A-Frame `<a-animation>` is using. `anime.js` was a one-and-done library and has some shortcomings.

**Comment by radenui** [comment]
Just recalculated the config at execution time...

**Comment by ngokevin** [comment]
thanks!

**Comment by radenui** [comment]
Hi Kevin,

Seems like this re-appeared [here](https://github.com/ngokevin/kframe/commit/7c092636744db20dd0df6b90616190ce4b4c3859).
Interested about a PR ?
Thanks,
Arthur
