### ISSUE TITLE
Trouble running Text component on A-Frame 0.4.0

### ISSUE THREAD

**Issue by Twila27** [ngokevin/kframe#31]
Greetings! WebVR newcomer trying to work through the A-Frame starter guide using Firefox 50.1.0, finally got down to text components which sent me here.

In running the example code under Browser Installation on https://www.npmjs.com/package/aframe-text-component over at https://twila27.github.io/vr/aframe/3dtext.html, it reports back that:

```
TypeError: _[t].toShapes is not a function[Learn More] --  aframe-text-component.min.js:1:2851
uncaught exception: The font #optimerBoldFont with normal weight and normal style is missing. -- (unknown)
```

Hope this helps!
Benjamin D. Gibson

**Comment by ngokevin** [comment]
Use the latest version of the text component

```npm install -g angle && angle install aframe-text-component```

**Comment by ngokevin** [comment]
i'll update the readme thanks!
