### ISSUE TITLE
[components/animation] animation seems to add to previous animation after remove

### ISSUE THREAD

**Issue by vrimaginar** [ngokevin/kframe#38]
Set an animation on, for instance, a-box with rotation: 0 360 0. Remove the animation with el.removeAttribute('animation') and add an animation, with setAttribute,to the same element with rotation: 360 0 0. This will result in a rotation: 360 360 0 when you see the scene.

It seems that removing the animation leaves some leftover from the properties set.

You can also, after removing the animation, add the same animation again with setAttribute. This will result in an animation with twice the duration.

**Comment by madebynoam** [comment]
I think my proposed changes (in issue #58) fix this issue as well: 

Quick test on glitch:
https://rel-anime-js-attr-test.glitch.me/
https://glitch.com/edit/#!/rel-anime-js-attr-test

Click the image and the y will rotate 45deg.
Click the gray button (it will remove the original animation and set a new one with an x rotation instead)
Click the image and the correct x rotation animation should play.
