### ISSUE TITLE
[components/animation] alternate is switching incorrectly in > 3.0.4

### ISSUE THREAD

**Issue by kellyselden** [ngokevin/kframe#39]
Using https://github.com/aframevr/360-image-gallery-boilerplate
The alternate function after 3 clicks in 3.0.4 goes:
out-in => out-in => out-in
in >= 3.1.0 goes:
out-in => in-out => out-in

The difference in these versions is animejs 1.1.1 => 1.1.3. It may be a regression there, or with code interfacing with that lib.

**Comment by kellyselden** [comment]
After more investigation, it looks like this was introduced in 3.1.0 with https://github.com/ngokevin/kframe/commit/b3d2ffc2f6d7efac1833bc7d39053498769460ee#diff-9be9c22b31d704c9bae772fdd003c1baR131

and is fixed in master with #29.

Do you mind releasing this?

**Comment by ngokevin** [comment]
I've released 3.2.2 thanks
