### ISSUE TITLE
Text component incompatible with A-Frame 0.5.0

### ISSUE THREAD

**Issue by i3games** [ngokevin/kframe#40]
This text component clashes with the new internal text component in A-Frame 0.5.0.

Including it via `<script src="aframe-text-component.js"></script>`
 yields:

"Error: The component `text` has been already registered. Check that you are not loading two versions of the same component or two different components of the same name."

**Comment by ngokevin** [comment]
Fixed https://github.com/ngokevin/kframe/tree/master/components/text-geometry
