### ISSUE TITLE
Template component triggers deprecation warning in A-Frame 0.5.0

### ISSUE THREAD

**Issue by i3games** [ngokevin/kframe#41]
The template component triggers the following warning in A-Frame 0.5.0:

"core:propertyTypes:warn `src` property type is deprecated. Use `asset` instead."

**Comment by ngokevin** [comment]
No longer happens, or if wasn't the template component. The template component does not have any src/asset prop types

**Comment by i3games** [comment]
Alright, it was a component in my template.
