### ISSUE TITLE
Change "to" without restarting animation

### ISSUE THREAD

**Issue by msj121** [ngokevin/kframe#5]
I can change the "to" in animation.data.to. Then I call animation.update().

Sadly this stops the previous animation. It would be nice to be able to change the to in the middle and animate accordingly.

**Comment by ngokevin** [comment]
Maybe remove the current animation, then add a different one for now

**Comment by msj121** [comment]
The problem is that if it is in the middle of an animation it will abruptly stop and then start and go to the new "to" animation

**Comment by ngokevin** [comment]
i don't know how we'd tell it to abruptly change the animation, but keep it smooth.

you'd have to pause it when appropriate, update the animation for transition period, and update the animation to your new `to`
