### ISSUE TITLE
aframe-layout-component: line layout along Y and Z axis

### ISSUE THREAD

**Issue by st3wang** [ngokevin/kframe#51]
The line layout seems to be limited to X axis only. It would be nice to support line layout along Y and Z.

**Comment by weddingdj** [comment]
Agreed. In order to achieve a line along the Y axis, I rotated the group by 90 degrees and each element by -90. ;-)

**Comment by ngokevin** [comment]
I think rotating it is sufficient than expanding the API?

**Comment by weddingdj** [comment]
For me rotating is ok.

**Comment by ngokevin** [comment]
Actually, I will work on this because this is preferable to rotating. Rotating changes the whole object transform which can be annoying.

**Comment by ngokevin** [comment]
Fixed.

`layout="type: circle; plane: xy"`
`layout="type: line; plane: yz"`
`layout="type: box; plane: xz"`
