### ISSUE TITLE
[components/reverse-look-controls] scene doesn't pan on Mobile Safari

### ISSUE THREAD

**Issue by doughamlin** [ngokevin/kframe#54]
Using Aframe 0.5.0 and the reverse-look-controls component on Mobile Safari (iOS 10.3) results in a scene that can't be dragged and doesn't respond to device orientation.

CodePen: http://codepen.io/doughamlin/pen/PpgPxw

**Comment by ngokevin** [comment]
A-Frame supports `lookControls="reverseMouseDrag: true" ` now, I can delete the component.
