### ISSUE TITLE
Is it possible to use this to animate visibility?

### ISSUE THREAD

**Issue by estevancarlos** [ngokevin/kframe#61]
`<a-entity scale="1 1 1" visible="true" animation="property: visible; dur: 1250; loop: true; to: false">`

Should that code above animate visibility? If so then that aspect of this plugin may not be working.

**Comment by ngokevin** [comment]
I'll look into it later, but it doesn't really make sense to animate a boolean value. I'd use the event-set component (https://github.com/ngokevin/kframe/tree/master/components/event-set) or some simple JS to toggle/flicker visibility instead

**Comment by estevancarlos** [comment]
Well, certainly most of the parameters available won't make sense in this case. Can't tween boolean values. But as an animation concept the idea is just to allow for something to be true and false through a loop. I would try "scale" (scale to an invisible size) but setting that duration causes a problem. 

I'll do straight JS then.

**Comment by ngokevin** [comment]
Something like:

```js
AFRAME.registerComponent('flicker', {
  tick: AFRAME.utils.throttleTick(function (t) {
    this.el.setAttribute('visible', !this.el.getAttribute('visible'));
  }, 1000);
});

<a-box flicker>
```

**Comment by estevancarlos** [comment]
Cool, thanks. I'm still learning how to write components so I'll use this as a first exercise. Thanks again.

**Comment by ngokevin** [comment]
Now it can `property: visible; from: true; to: false`
