### ISSUE TITLE
[components/template] Children of root object get deleted on update

### ISSUE THREAD

**Issue by haydenjameslee** [ngokevin/kframe#65]
I'd like to use the template component on elements like this:

```html
<a-entity id="parent" template="...">
    <a-entity id="child"></a-entity>
</a-entity>
```

However due to this code https://github.com/ngokevin/kframe/blob/master/components/template/index.js#L51 the #child element is removed when update gets triggered.

Also it seems `oldData` is always truthy because aframe passes an empty object on the first update call, so child elements even get deleted on load.

Maybe the template component could keep track of children created by itself, and only delete those? An option to just not remove children would work for my use case too. 

In the meantime I'll just be using a forked version with those lines commented out in https://github.com/haydenjameslee/networked-aframe 0.2

**Comment by ngokevin** [comment]
Would it make sense to do:

```
<a-entity id="parent">
   <a-entity template></a-entity>
    <a-entity id="child"></a-entity>
</a-entity>
```

**Comment by haydenjameslee** [comment]
Beautiful! That solves some other problems too :)
