### ISSUE TITLE
Error: The component `text` has been already registered. Check that you are not loading two versions of the same component or two different components of the same name.

### ISSUE THREAD

**Issue by scott-plutovr** [ngokevin/kframe#66]
When requiring kframe with aframe already on the page (also tried k-frame). We tried 0.3.0 and 0.3.2-beta2.

Using Nightly 55.0a1 (2017-05-22) (64-bit) on Windows 10.

Is this conflicting with the built in aframe "text" component?

**Comment by ngokevin** [comment]
Include the components individually. The kframe package is gone
