### ISSUE TITLE
Firebase Component Won't Utilize Same Asset

### ISSUE THREAD

**Issue by fisherinnovation** [ngokevin/kframe#68]
I am trying to implement the Firebase component to share elements between users.

Example. I have a box in a scene which has the `firebase-broadcast` attribute appended to it. When two people enter the scene, the element is then created for each user (looking at the code, this make sense). However I would like to have the second user utilize the same box asset data from the first user so, for instance, they could toss the same box back and fourth to each other. 

Is this implementation possible with the current status of the component?

**Comment by evgenious** [comment]
Also have been looking for this options and there have been a WIP before the component have been moved: https://github.com/ngokevin/aframe-firebase-component/issues/1
Regarding the added value its an important feature we should work on :)

**Comment by protyze** [comment]
Not sure how active this component is maintained currently. But I have worked on a "firebase-synch" component for a project. I would be interested to merge it with the WIP of ngokevin/aframe-firebase-component#1 and finally integrate a working version into this "official" firebase component. Has there been any progress on the WIP in the meantime by @ngokevin we should consider?

**Comment by ngokevin** [comment]
Yeah, I'll try to have time to merge changes in. But I'm a bit bearish one using Web Sockets for multiuser in general. Searching for ways we can get better backends (e.g., exposing browser UDP).

**Comment by ngokevin** [comment]
I don't think I'll continue to work on this Firebase implementation, I don't think it'll scale well for shared objects and physics, but I'll experiment with better multiuser solutions.

**Comment by protyze** [comment]
Yeah I ran into performance issues here as well and with networked-aframe it seems to run much smoother. Maybe it could be optimized. But ok. Let's move on. It's an easy solution to quickly prototype multi-user though.

**Comment by ngokevin** [comment]
If you have anything, I can check it out!
