### ISSUE TITLE
Installing the animation component from npm gives outdated anime dependency

### ISSUE THREAD

**Issue by gregfagan** [ngokevin/kframe#69]
After `npm install`ing this package, I appear to have gotten an outdated animejs.

I checked the `package.json` in my `node_modules` directory:

```
...
  "dependencies": {
    "animejs": "^1.1.0"
  },
...
  "version": "3.2.5"
```

This seems to be an error, as it doesn't match the source:

https://github.com/ngokevin/kframe/blob/master/components/animation/package.json#L35

I was hoping to use the custom bezier easing functionality of the more recent versions of anime. I'm not sure what went wrong here, does it need to be redeployed to npm? Even if I had the right version of anime, would it work? I tried a local edit to pull in anime `"2.0.2"` but had errors when running it.

**Comment by ngokevin** [comment]
I don't think I've published with the Anime v2 yet...you can grab it from GitHub maybe. I'm still need to add more tests and fix things

**Comment by gregfagan** [comment]
My mistake. Thanks for the suggestion.
