### ISSUE TITLE
Animation & State (feature request)

### ISSUE THREAD

**Issue by msj121** [ngokevin/kframe#7]
I am hoping to only have animations triggered based off of state. This will allow animations to be more "aware" and be able to easily tell a story. Not at all times does looking at a character do the same thing, sometimes it makes them run, sometimes it makes them talk based off of the state.

In the schema add the ability to write the required state for the animation to trigger. Then even if a separate component that controls state, with event-set.

Additionally if possible allow animation component to change the state at end of animation/at the beginning.

Unless you think there is a better way to do this? This would really expand the capability of AFrame imo.

**Comment by ngokevin** [comment]
A-Frame emits an event whenever state changes. You can use that event as the `startEvents` on an animation.
