### ISSUE TITLE
Look-At component v0.5.1 broken 

### ISSUE THREAD

**Issue by i3games** [ngokevin/kframe#75]
line 51:
bug:
`var isCoordinates = coordinates.isCoordinates;`

correct:
`var isCoordinates = coordinates.isCoordinate;`

**Comment by ngokevin** [comment]
Are you sure you're using 0.5.1 https://github.com/ngokevin/kframe/blob/master/components/look-at/dist/aframe-look-at-component.js#L51 ?

**Comment by i3games** [comment]
Ah, I did a `fetch` but forgot to `pull`.
