### ISSUE TITLE
[animation] consider anime.js key frames support

### ISSUE THREAD

**Issue by andreasplesch** [ngokevin/kframe#79]
https://github.com/juliangarnier/anime#keyframes
While it is possible to use events to define a sequence of animations, being able to declare key frames as component properties would be more concise and intuitive.
A possible interface could be  arrays as values for each property where each array element corresponds to a key frame:
```
animation__height="property: geometry.height; dur: 200, 100, 400; loop: true; to: 0.18, 0.5, 0.1"
```
loop and dir would still apply to the complete animation which includes all key frames.

**Comment by ngokevin** [comment]
I'd do this using AFRAME.ANIME versus declarative.

**Comment by andreasplesch** [comment]
Ok, a decision. I just thought with A-Frame being declarative in the first place, it would be natural to extend to keyframes as arrays.

**Comment by ngokevin** [comment]
it's only declarative at the outermost/top layer, doesn't extend to doing everything declaratively

**Comment by andreasplesch** [comment]
Key frames are considered more internal, or perhaps an advanced feature
then. Fair enough, a choice.
