### ISSUE TITLE
[Animation] Chain animations

### ISSUE THREAD

**Issue by vrimaginar** [ngokevin/kframe#85]
Hi,

I try to chain an animation by listening to the animation__[ID]-complete event but it is not working.

`<a-box position="0 0 0" color="red" class="clickable"
				animation="property: position; from: 0 0 0; to: 4 0 0; dur: 5000; startEvents: click"
				animation__yes="property: rotation; from: 0 0 0; to: 0 0 -360; dur: 5000; startEvents: click"></a-box>
`
				
`<a-box position="0 2 0" color="yellow" 
				animation="property: position; from: 0 2 0; to: 0 0 0; dur: 5000; startEvents: animation__yes-complete"></a-box>`

Am I doing something wrong? 

It is working when you attach an eventlistener to the first box and listen for animation__[ID]-complete.

**Comment by ngokevin** [comment]
https://www.npmjs.com/package/aframe-animation-timeline-component
