### ISSUE TITLE
[Animation] Dynamic `to` or (passing functions to params)?

### ISSUE THREAD

**Issue by jlieb10** [ngokevin/kframe#91]
I am new to this project and love the Animation component, but I am having difficulty using to dynamically change colors.

Note: I am also using this within the context of aframe-react if that matters.

Here is an example to illustrate what I am trying to do: 
```
class App extends React.Component {
  changeColor() {
    const colors = ['#ff0000', '#ff5a00', '#ff9a00', '#ffce00', '#ffe808'];
    return colors[Math.floor(Math.random() * colors.length)];
  }

  render () {
    return (
      <Scene>
        <Entity id="wall1"
          primitive="a-box"
          color='#ff0000'
          height="10"
          width="20"
          depth=".1"
          opacity="0.5"
          rotation="0 0 0"
          position="0 5 -10"
          animation={`
            property: color; 
            dir: alternate; 
            dur: 250;
            loop: true;
            to: ${this.changeColor()};
          `}
        />
      </Scene>
    );
  }
}
```

I was hoping that when the animation component ran, it would make new calls to this.changeColor() but it seems that only is called once. I tried passing a complete function to the `to` param, but of course this is not what it accepts.

Any advice appreciated!

**Comment by codechikbhoka** [comment]
Don't know about proper method but I have been using this workaround to have this functionality. 

/*
Note: 
  -on this.data update, we are recreating a-animation element and replacing
   last a-animation. We are unable to update a-animation's 'from', 'to' etc 
   values thats why we are replacing preview a-animation with new a-animation
   with updated values.
  -If begin is not defined, then animation will be played on each
  update.
  -playAnimOnUpdate: This property is need because on this.data update we are 
  recreating a-animation, there is no way to begin animation by triggering
  'begin' event.(Race condition problem.)
*/
AFRAME.registerComponent("vs-animation", {
    schema: {
        id: { type: "string", default: "" },
        attribute: { type: "string" },
        begin: { type: "string", default: "" },
        delay: { type: "number", default: 0 },
        direction: { type: "string", default: "normal" },
        dur: { type: "number", default: 1000 },
        easing: { type: "string", default: "ease" },
        end: { type: "string", default: "" },
        fill: { type: "string", default: "forwards" },
        from: { type: "string" },
        repeat: { type: "number", default: 0 },
        to: { type: "string" },
        playAnimOnUpdate: { type: "boolean", default: false }
    },

    init: function() {
        // set this.data.from to current value if it is not set.
        if (!this.data.from) {
            this.data.from = this.el.getAttribute(this.data.attribute);
        } else {
            this.animElem = this.createAnim();
            this.el.parentNode.appendChild(this.animElem);
        }
    },

    update: function() {
        var updatedAnimElem = this.createAnim();
        if (this.animElem) {
            this.el.parentNode.replaceChild(updatedAnimElem, this.animElem);
        } else {
            this.el.parentNode.appendChild(updatedAnimElem);
        }
        if (this.data.playAnimOnUpdate && this.data.begin) {
            this.el.parentNode.emit(this.data.begin);
        }
        this.animElem = updatedAnimElem;
    },

    play: function() {},

    pause: function() {},

    remove: function() {},

    createAnim: function() {
        var animElem = document.createElement("a-animation");
        animElem.setAttribute("id", this.data.id);
        animElem.setAttribute("attribute", this.data.attribute);
        animElem.setAttribute("begin", this.data.begin);
        animElem.setAttribute("delay", this.data.delay);
        animElem.setAttribute("direction", this.data.direction);
        animElem.setAttribute("dur", this.data.dur);
        animElem.setAttribute("easing", this.data.easing);
        animElem.setAttribute("end", this.data.end);
        animElem.setAttribute("fill", this.data.fill);
        animElem.setAttribute("from", this.data.from);
        animElem.setAttribute("repeat", this.data.repeat);
        animElem.setAttribute("to", this.data.to);
        return animElem;
    }

});

**Comment by codechikbhoka** [comment]
You can write your own component for this. Take all the attributes for the a-animation as an input to that component and create a <a-animation> element using those. Now in the update function of that component you can create a new a-animation element and replace the old one. Don't know if this is the most optimal way or proper way, but this works

**Comment by ngokevin** [comment]
this isn't how react works.

if you want to dynamically change color, listen to the animationcomplete event and then modify the `to`.
