### ISSUE TITLE
[state] example requires https://github.com/aframevr/aframe/commit/6cbdac950f7457c7d09a8fecddc46018b443a222 instead of 0.6.1 to accept number value

### ISSUE THREAD

**Issue by remkoboschker** [ngokevin/kframe#95]

**Comment by ngokevin** [comment]
Yeah, I updated A-Frame text component to accept numbers. If you want to do the same on 0.6.1, you can convert the number to strings within the state in order to keep the automatic binding.

```
newState.score = (parseInt(newState.score, 10) + action.score).toString();
```
